trigger:
- master

pool:
  OPTIX Builder 

variables:
  - name: 'TARGET_IP'
    value: '192.168.1.200'
  - name: 'TARGET_USER'
    value: 'admin'
  - name: 'FT_OPTIX_CLI'
    value: 'C:\\Program Files\\Rockwell Automation\\FactoryTalk Optix\\Studio 1.6.0.557\\FTOptixStudio'

steps:
  - script: |
      echo "Repo root: $(Build.SourcesDirectory)"
      dir "$(Build.SourcesDirectory)"
    displayName: 'Print repo root'

  - script: |
      echo Building and exporting HMI project...
      "$(FT_OPTIX_CLI)" deploy "$(Build.SourcesDirectory)/MyHMI_Template_Unencrypted.optix" --ip-address=$(TARGET_IP) --username=$(TARGET_USER)
    displayName: 'Export and deploy project to target machine'

  - script: |
      echo Building and exporting HMI project...
      "$(FT_OPTIX_CLI)" export "$(Build.SourcesDirectory)/MyHMI_Template_Unencrypted.optix" --location="$(Build.SourcesDirectory)/build" --platform=Win32_x64
    displayName: 'Export and deploy project to target machine'

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifact"
    inputs:
      PathtoPublish: "$(Build.SourcesDirectory)/build"
      ArtifactName: "optix"

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/tests/HmiTesting.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: '$(Build.SourcesDirectory)/tests/HmiTesting.sln'

  - script: |
      pwsh $(Build.SourcesDirectory)/tests/HmiTesting.PlaywrightTests/bin/Debug/netX/playwright.ps1 install
    displayName: 'Install Browser'


  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '$(Build.SourcesDirectory)/tests/HmiTesting.PlaywrightTests/HmiTesting.PlaywrightTests.csproj'
      arguments: '--no-build --logger trx'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/TestResults/*.trx'
      testResultsFormat: 'VSTest'
      failTaskOnFailedTests: true     

  - script: |
      echo Deployment pipeline completed.
    displayName: 'Finish'
