Name: Security
Id: g=2b6a4b1a278fbbd7e1763e4e43973e25
Type: FolderType
Children:
- Name: CoT_User
  Id: g=c89965a6a1d6d5e753a3ee609b2b2fda
  Supertype: UserType
  Children:
  - Name: icon
    Id: g=b7fe20afb795ffb73e8f169c6defff46
    Type: BaseDataVariableType
    DataType: ResourceUri
  - Name: userName
    Id: g=9547f74b7fe1fc99ad6b9418cc0509df
    Type: BaseDataVariableType
    DataType: String
