@startuml
!include .\\HmiTesting.PlaywrightTests\UnitTest1.puml
!include .\\src\HmiTesting.Core\IControl.puml
!include .\\src\HmiTesting.Core\IHmiPage.puml
!include .\\src\HmiTesting.Core\IHmiPageArea.puml
!include .\\src\HmiTesting.Core\INavigator.puml
!include .\\src\HmiTesting.Core\IOpcUaClient.puml
!include .\\src\HmiTesting.Core\IOpcUaSession.puml
!include .\\src\HmiTesting.OpcUa\OpcUaClient.puml
!include .\\src\HmiTesting.OpcUa\OpcUaSession.puml
!include .\\src\HmiTesting.Web.Components\ButtonControl.puml
!include .\\src\HmiTesting.Web.Components\ContentElement.puml
!include .\\src\HmiTesting.Web.Components\GroupBox.puml
!include .\\src\HmiTesting.Web.Navigation\HmiPageTaskExtensions.puml
!include .\\src\HmiTesting.Web.Navigation\Navigator.puml
!include .\\src\HmiTesting.Web.Pages\HmiPage.puml
!include .\\src\HmiTesting.Web.Pages\HmiPageArea.puml
!include .\\src\HmiTesting.Core\DTOs\LocatorNodeId.puml
!include .\\src\HmiTesting.Core\enums\LayoutType.puml
!include .\\src\HmiTesting.Core\helper\OpcUaHelper.puml
!include .\\src\HmiTesting.Core\helper\PathHandler.puml
!include .\\src\HmiTesting.Core\helper\PlaywrightHelper.puml
!include .\\HmiTesting.PlaywrightTests\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\HmiTesting.PlaywrightTests\obj\Debug\net8.0\HmiTesting.PlaywrightTests.AssemblyInfo.puml
!include .\\HmiTesting.PlaywrightTests\obj\Debug\net8.0\HmiTesting.PlaywrightTests.GlobalUsings.g.puml
!include .\\src\HmiTesting.Core\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\src\HmiTesting.Core\obj\Debug\net8.0\HmiTesting.Core.AssemblyInfo.puml
!include .\\src\HmiTesting.Core\obj\Debug\net8.0\HmiTesting.Core.GlobalUsings.g.puml
!include .\\src\HmiTesting.OpcUa\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\src\HmiTesting.OpcUa\obj\Debug\net8.0\HmiTesting.OpcUa.AssemblyInfo.puml
!include .\\src\HmiTesting.OpcUa\obj\Debug\net8.0\HmiTesting.OpcUa.GlobalUsings.g.puml
!include .\\src\HmiTesting.Web.Components\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\src\HmiTesting.Web.Components\obj\Debug\net8.0\HmiTesting.Web.Components.AssemblyInfo.puml
!include .\\src\HmiTesting.Web.Components\obj\Debug\net8.0\HmiTesting.Web.Components.GlobalUsings.g.puml
!include .\\src\HmiTesting.Web.Navigation\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\src\HmiTesting.Web.Navigation\obj\Debug\net8.0\HmiTesting.Web.Navigation.AssemblyInfo.puml
!include .\\src\HmiTesting.Web.Navigation\obj\Debug\net8.0\HmiTesting.Web.Navigation.GlobalUsings.g.puml
!include .\\src\HmiTesting.Web.Pages\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\src\HmiTesting.Web.Pages\obj\Debug\net8.0\HmiTesting.Web.Pages.AssemblyInfo.puml
!include .\\src\HmiTesting.Web.Pages\obj\Debug\net8.0\HmiTesting.Web.Pages.GlobalUsings.g.puml
@enduml